webtalk_init -webtalk_dir /media/andi/part_vivado/PRJ/myPrj1/myPrj1/myPrj1.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-11-29 16:57:46" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212336542_0_0_961" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "t85tj1r4cktprrju7ksqftspps" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.7 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2501.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "8" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14,095 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1638200798000" -context "sdk\\\\bsp/1638200798000"
webtalk_add_data -client sdk -key hwid -value "1636036000000" -context "sdk\\\\bsp/1638200798000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1638200798000"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\bsp/1638200798000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1638200798000"
webtalk_add_data -client sdk -key uid -value "1638200804000" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key hwid -value "1636036000000" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key bspid -value "1638200798000" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key apptemplate -value "peripheral_tests" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key projSize -value "402.04296875" -context "sdk\\\\application/1638200804000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1638201466001"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1638201466001"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1638201466001"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1638201466001"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1638201466001"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1638201466001"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1638201466001"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1638201466001"
webtalk_transmit -clientid 3273027711 -regid "212336542_0_0_961" -xml /media/andi/part_vivado/PRJ/myPrj1/myPrj1/myPrj1.sdk/webtalk/usage_statistics_ext_sdk.xml -html /media/andi/part_vivado/PRJ/myPrj1/myPrj1/myPrj1.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /media/andi/part_vivado/PRJ/myPrj1/myPrj1/myPrj1.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
