webtalk_init -webtalk_dir /media/andi/part_vivado/PRJ/TestPrj/SoC_Design_Lab/XSDK_Workspace/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-12-06 18:33:35" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212336542_0_0_961" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dkq27fs4desmg6k78n01fstoa7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.7 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2501.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "8" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14,095 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1638801085000" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1638801085000"
webtalk_add_data -client sdk -key uid -value "1638801259000" -context "sdk\\\\application/1638801259000"
webtalk_add_data -client sdk -key os -value "linux" -context "sdk\\\\application/1638801259000"
webtalk_add_data -client sdk -key apptemplate -value "linux_hello_world" -context "sdk\\\\application/1638801259000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1638801259000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1638801259000"
webtalk_add_data -client sdk -key Procused -value "" -context "sdk\\\\application/1638801259000"
webtalk_add_data -client sdk -key projSize -value "70.51171875" -context "sdk\\\\application/1638801259000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1638812015090"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1638812015090"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1638812015090"
webtalk_add_data -client sdk -key DebugCount -value "32" -context "sdk\\\\bsp/1638812015090"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1638812015090"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1638812015090"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1638812015090"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1638812015090"
webtalk_transmit -clientid 2510324870 -regid "212336542_0_0_961" -xml /media/andi/part_vivado/PRJ/TestPrj/SoC_Design_Lab/XSDK_Workspace/webtalk/usage_statistics_ext_sdk.xml -html /media/andi/part_vivado/PRJ/TestPrj/SoC_Design_Lab/XSDK_Workspace/webtalk/usage_statistics_ext_sdk.html -wdm /media/andi/part_vivado/PRJ/TestPrj/SoC_Design_Lab/XSDK_Workspace/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
